### PR TITLE
Install using the current users security principal

### PR DESCRIPTION
**Pull request by khyberspache**

### CODE REVIEW

**Comment by privateducky** [comment]
@makk94 @mireaulf will wait on your thoughts

**Comment by makk94** [comment]
Does this make the probe itself run w/ highest privileges too?

**Comment by khyberspache** [comment]
> Does this make the probe itself run w/ highest privileges too?

No the probe runs with whatever privileges the current users token has

**Comment by makk94** [comment]
I just ran this on a Windows 16 VM and after rebooting got:
`Task Scheduler did not launch task "\Prelude Detect"  because user "EC2AMAZ-9BFFCMC\Administrator" was not logged on when the launching conditions were met. User Action: Ensure user is logged on or change the task definition to allow launching when user is logged off.`

**Comment by khyberspache** [comment]
> I just ran this on a Windows 16 VM and after rebooting got:
> `Task Scheduler did not launch task "\Prelude Detect" because user "EC2AMAZ-9BFFCMC\Administrator" was not logged on when the launching conditions were met. User Action: Ensure user is logged on or change the task definition to allow launching when user is logged off.`


We need to toggle the task definition to support ` change the task definition to allow launching when user is logged off.`

I'm getting more errors with the current pattern in an Active Directory environment

**Pull request closed without merging**
