### PR TITLE
feat: updating JS SDK to include deleteProbes

### PR DESCRIPTION
**Pull request by stephanwampouille**
This is my first attempt at adding the deleteProbes func for the endpoint

The body is based on my convo with @mireaulf and him informing me that the body takes an `id` being the `endpoint_id` of the probe.

### CODE REVIEW

**Review by privateducky — APPROVED** [review]
@kenrick good by you?

**Comment by kenrick** [comment]
bump you package.json verison as well @stephanwampouille

**Comment by kenrick** [comment]
@stephanwampouille delete your yarn files

**Review by kenrick — APPROVED** [review]
Looks good @stephanwampouille @privateducky

**Pull request merged**
