### PR TITLE
export endpoint token between demo and install to reuse same token

### PR DESCRIPTION
**Pull request by makk94**
re: https://github.com/preludeorg/libraries/issues/221

will update powershell in a separate PR

### CODE REVIEW

**Review by privateducky — COMMENTED** [review]
I don't understand the change set here; most of it is renaming the env var, where the only applicable line appears to be 65 (export VARIABLE) in the demo.sh.

**Comment by makk94** [comment]
> I don't understand the change set here; most of it is renaming the env var, where the only applicable line appears to be 65 (export VARIABLE) in the demo.sh.

That's all correct. The renaming is just for consistency/ I think it's clearer. The exporting is the functional change - it goes with the changes in install.sh.   If user chooses to install a probe after running the demo script, the demo script exports ENDPOINT_TOKEN. meanwhile install.sh checks if ENDPOINT_TOKEN is set as an env variable, and if so, will reuse that token instead of registering a new endpoint

**Comment by privateducky** [comment]
Why ENDPOINT TOKEN instead of PRELUDE though? Referring to the same thing by two names across our code base can get confusing. (I initially chose PRELUDE, so all our env vars, currently 3, could be spotted easily).

**Comment by makk94** [comment]
I just think ENDPOINT_TOKEN is more explicit - I've had multiple people just at Prelude ping me that "probes aren't working" b/c they are using an admin token instead of an endpoint token. what about PRELUDE_ENDPOINT_TOKEN across the board? It matches PRELUDE_ACCOUNT_ID and PRELUDE_ACCOUNT_SECRET better

 (it also nags at me that we use "secret" when referring to accounts and "token" for endpoints, not sure if you feel the same ha)

**Comment by privateducky** [comment]
We can definitely look at renaming these vars but let's separate that from this PR.

Renaming the vars is a larger change: docs, code, probes, handling existing deployments, etc, so while I'm all for it, we should isolate why someone would get confused first (poor docs, poor error messaging, etc).

**Comment by makk94** [comment]
Moved demo.sh back to PRELUDE_TOKEN (though that wasn't a public variable/argument so it shouldn't have been a problem...) 

Also moved ENDPOINT_TOKEN in install.sh to an arg to stay consistent with other args there

**Review by privateducky — CHANGES_REQUESTED** [review]
I don't want to invent new env var names in one spot, so let's use our existing names:
- PRELUDE_TOKEN
- PRELUDE_API
- PRELUDE_CA

For account ID/token pairs, we currently do not leverage these in env vars, so we can invent something for our install/demo scripts, assuming they are all consistent. PRELUDE_ACCOUNT_ID / PRELUDE_ACCOUNT_SECRET are fine by me, although the latter is likely odd if the user is required to send in a 'token' as a header.

**Comment by makk94** [comment]
> I don't want to invent new env var names in one spot, so let's use our existing names:
> 
> * PRELUDE_TOKEN
> * PRELUDE_API
> * PRELUDE_CA
> 
> For account ID/token pairs, we currently do not leverage these in env vars, so we can invent something for our install/demo scripts, assuming they are all consistent. PRELUDE_ACCOUNT_ID / PRELUDE_ACCOUNT_SECRET are fine by me, although the latter is likely odd if the user is required to send in a 'token' as a header.

I'm not adding any new env vars in this PR. Are you requesting that the install.sh argument descriptor names match the env vars? Ie. you want the help menu to look like:
```
mahinakaholokula@Mahinas-MacBook-Pro libraries % ./shell/probe/install.sh -h

Usage: install.sh [-h] -n PROBE_NAME

  -h                          Shows Usage
  -n PROBE_NAME               Probe Name; Default: nocturnal
  -t PRELUDE_TOKEN            Endpoint Token; Use PRELUDE_ACCOUNT_ID and PRELUDE_ACCOUNT_SECRET to register a new endpoint
  -a PRELUDE_ACCOUNT_ID       Prelude Account Id; asdf
  -s PRELUDE_ACCOUNT_SECRET   Prelude Account Secret; 
  -e ENDPOINT_ID              Endpoint Id; Default: Mahinas-MacBook-Pro.local
```

**Comment by makk94** [comment]
@privateducky Originally was pushing the endpoint_token through so that a re-run of the demo script would work (endpoint token would still be active). With the trouble were having and looking at https://github.com/preludeorg/range/issues/13 - I'm just going to switch to re-registering the endpoint in install.sh. The demo script can pass through the endpoint id and install.sh will re-register with same endpoint name/ get a new token back

**Comment by privateducky** [comment]
@makk94 exactly; match the env var names with the names in the params.

**Pull request closed without merging**
