### PR TITLE
add plaintext option

### PR DESCRIPTION
**Pull request by makk94**
so everyone can have their precious jq
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --plaintext detect activity -d 1 | jq
[
  {
    "id": "3645c6a7-7df8-4682-b0e6-ecc3bc9c0ecc",
    "date": "2023-02-28 19:24:50.008086",
    "test": "39de298a-911d-4a3b-aed4-1e8281010a9a",
    "endpoint_id": "beech",
    "status": 100,
    "dos": "linux-x86_64",
    "tags": [
      "tag1"
    ]
  }
]

```

### CODE REVIEW

**Comment by privateducky** [comment]
I'm not totally against this... but I am interested in alternative options.
One prime one may be to remove the rich pretty/print of json and revert to Python's normal json printing, which we can do "pretty". the CLI could use a shared function for this pretty print capability, such as:
```
pretty = lambda s: json.dumps(s, indent=4)
```
so we could do something like:
```
print(pretty(json_str))
```

**Review by privateducky — CHANGES_REQUESTED** [review]
new plan...

**Comment by makk94** [comment]
Confused on how this fixes the problem…

**Comment by privateducky** [comment]
> Confused on how this fixes the problem…

I think the pretty print with built in json would work with JQ - but would need to test. If yes, it means we wouldn't need to use an extra flag.

**Comment by privateducky** [comment]
If that doesn't work, I'd say we just avoid pretty printing from the CLI and document that people should use a wrapper like JQ to do it.

**Comment by makk94** [comment]
The issue isn’t the pretty print, it’s your fun little spinner ha

**Comment by privateducky** [comment]
> The issue isn’t the pretty print, it’s your fun little spinner ha

Gotcha. In that case, I won't worry about this for now. You can pipe the output into a file atm.

**Pull request closed without merging**
