### PR TITLE
remove the js sdk

### PR DESCRIPTION
**Pull request by makk94**
can I really..?

### CODE REVIEW

**Comment by stephanwampouille** [comment]
ummmI feel like I missed something 🤓☝️(I was not paying attention in standup, too focused on my ticket)

**Comment by keitharobertson** [comment]
> ummmI feel like I missed something 🤓☝️(I was not paying attention in standup, too focused on my ticket)

We got the go ahead to delete this a few weeks ago. This is Mahina's therapy.

**Comment by keitharobertson** [comment]
> > ummmI feel like I missed something 🤓☝️(I was not paying attention in standup, too focused on my ticket)
> 
> We got the go ahead to delete this a few weeks ago. This is Mahina's therapy.

https://preludeorg.slack.com/archives/C03D6MCTF35/p1725479151223019?thread_ts=1725400582.503909&cid=C03D6MCTF35

**Review by keitharobertson — APPROVED** [review]

**Comment by kenrick** [comment]
Screenshot 2024-04-26 at 12 59 51 PM

**Review by kenrick — APPROVED** [review]

**Review by stephanwampouille — APPROVED** [review]
approved, i assume we will delete the npm package, is that a Patrick job?

**Comment by packplusplus** [comment]
> approved, i assume we will delete the npm package, is that a Patrick job?

sure?

**Review by packplusplus — APPROVED** [review]
:tombstone:

**Comment by matterpreter** [comment]
😍 😍 😍

**Comment by bfuzzy1** [comment]
🤭

**Comment by keitharobertson** [comment]
🥳 🎂 🎁

**Pull request merged**
