### PR TITLE
Update expected account object to fix sdk test

### PR DESCRIPTION
**Pull request by keitharobertson**

### CODE REVIEW

**Comment by stephanwampouille** [comment]
should you add the detections property as well or does it not matter for your tests (I haven't checked the test) ?

**Comment by keitharobertson** [comment]
> should you add the detections property as well or does it not matter for your tests (I haven't checked the test) ?

good point! Now I'm not sure why this passes

**Comment by keitharobertson** [comment]
> > should you add the detections property as well or does it not matter for your tests (I haven't checked the test) ?
> 
> good point! Now I'm not sure why this passes

heh it is looping over the expected items and making sure they are in the returned. So items returned, but not in the expected do not error.

**Comment by makk94** [comment]
> > > should you add the detections property as well or does it not matter for your tests (I haven't checked the test) ?
> > 
> > 
> > good point! Now I'm not sure why this passes
> 
> heh it is looping over the expected items and making sure they are in the returned. So items returned, but not in the expected do not error.

yeah, it's more of a _contains_ test than an exact match. not terribly sophisticated, but i didn't want to deal with difficult fields like timestamps and random ids or whatnot. you like it? ha

**Comment by makk94** [comment]
i have these changes in my PR too :) (just hadn't sent it to you yet)

**Review by makk94 — APPROVED** [review]

**Comment by keitharobertson** [comment]
> > > > should you add the detections property as well or does it not matter for your tests (I haven't checked the test) ?
> > > 
> > > 
> > > good point! Now I'm not sure why this passes
> > 
> > 
> > heh it is looping over the expected items and making sure they are in the returned. So items returned, but not in the expected do not error.
> 
> yeah, it's more of a _contains_ test than an exact match. not terribly sophisticated, but i didn't want to deal with difficult fields like timestamps and random ids or whatnot. you like it? ha

Yeah that makes sense!

**Pull request merged**
